sudo: required

language: node_js

services:
  - docker

#addons:
#  sauce_connect: true

env:
  global:
  - ENCRYPTION_LABEL: "7cec43065660"
  - COMMIT_AUTHOR_EMAIL: "sebastian.fuss@googlemail.com"

node_js:
  - "10"

before_install:

install:
  # Install the library deps
  - npm install
  # Lint the demo app
  - npm run lint

script:
  # Execute the tests
 - npm run test:ci

#after_success:
#  - ./deploy.sh

#after_script:
#  - docker stop ng2mwDemo
#  - docker rm ng2mwDemo
